const fs=require('fs');
console.log('Started');
fs.readFile('input.txt',(err,data)=>{
    if(err)
    {
        console.log(err);
    }
    console.log(data.toString());
})
console.log('Ended');
fs.readFile('input2.txt',function(err,data){
    if(err)
    {
        console.log(err);
    }
    else
    {
        console.log(data.toString());
    }
})